import React from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import { ArrowRight, Bath, Building2, CheckCircle2, ClipboardCheck, DoorOpen, Hammer, Home as HomeIcon, Languages, Mail, MapPin, Paintbrush, Phone, Shield, Sparkles, Utensils, Warehouse, Wrench } from "lucide-react";

type IconType = React.ComponentType<{ size?: number; className?: string }>;
type City = { name: string; slug: string; note: string; nearby: string };

const email = "brothersremodelingokc@gmail.com";

const services: Array<[string, string, IconType]> = [
  ["Kitchen Remodeling", "Cabinets, counters, backsplash, lighting, islands, flooring, layout improvements, and cleaner daily function.", Utensils],
  ["Bathroom Remodeling", "Showers, tubs, tile, vanities, fixtures, waterproofing details, ventilation, and better storage.", Bath],
  ["Interior Renovations", "Drywall, texture, trim, paint, doors, baseboards, accent walls, room updates, and layout changes.", HomeIcon],
  ["Flooring Installation", "LVP, tile, laminate, transitions, subfloor prep, and finish carpentry that ties the remodel together.", Hammer],
  ["Exterior Remodeling", "Siding, facade updates, decks, fences, exterior paint, curb appeal, windows, doors, and practical repairs.", DoorOpen],
  ["Additions, Garages & Conversions", "Added living areas, garage remodels, storage upgrades, offices, commercial spaces, and better use of square footage.", Building2],
  ["Outdoor Living Spaces", "Patios, exterior gathering areas, repairs, fencing, and improvements that make the outside more usable.", Warehouse],
  ["Repair & Maintenance", "Punch-list repairs, patching, painting, maintenance, and smaller details that keep a property sharp.", Wrench],
];
const serviceDetails = [
  { slug: "kitchen-remodeling", title: "Kitchen Remodeling", short: "Cabinets, counters, backsplash, lighting, islands, flooring, layout improvements, and cleaner daily function.", icon: Utensils, focus: "cabinet layout, countertops, backsplash, lighting, flooring, appliance placement, storage, and the way the kitchen connects to daily traffic", rooms: "kitchens, dining edges, pantry areas, laundry connections, and open living spaces" },
  { slug: "bathroom-remodeling", title: "Bathroom Remodeling", short: "Showers, tubs, tile, vanities, fixtures, waterproofing details, ventilation, and better storage.", icon: Bath, focus: "showers, tubs, tile, vanities, waterproofing, ventilation, storage, fixture placement, and clean finish details", rooms: "primary baths, hall baths, powder rooms, guest baths, and compact bathrooms" },
  { slug: "interior-renovations", title: "Interior Renovations", short: "Drywall, texture, trim, paint, doors, baseboards, accent walls, room updates, and layout changes.", icon: HomeIcon, focus: "drywall, texture, trim, paint, doors, baseboards, room openings, accent details, and layout improvements", rooms: "living rooms, bedrooms, hallways, offices, rental spaces, and whole-home interiors" },
  { slug: "flooring-installation", title: "Flooring Installation", short: "LVP, tile, laminate, transitions, subfloor prep, and finish carpentry that ties the remodel together.", icon: Hammer, focus: "floor removal, subfloor prep, LVP, laminate, tile, transitions, baseboards, and finish carpentry", rooms: "kitchens, baths, living rooms, bedrooms, hallways, garages, and rental properties" },
  { slug: "exterior-remodeling", title: "Exterior Remodeling", short: "Siding, facade updates, decks, fences, exterior paint, curb appeal, windows, doors, and practical repairs.", icon: DoorOpen, focus: "siding, trim, paint, doors, windows, decks, fences, exterior repairs, curb appeal, and weather-facing details", rooms: "front elevations, patios, side yards, backyards, garages, entries, and rental exteriors" },
  { slug: "additions-garages-conversions", title: "Additions, Garages & Conversions", short: "Added living areas, garage remodels, storage upgrades, offices, commercial spaces, and better use of square footage.", icon: Building2, focus: "added square footage, garage conversions, office spaces, storage, framing, insulation, drywall, flooring, and finish tie-ins", rooms: "garages, bonus rooms, additions, offices, workshops, and light commercial spaces" },
  { slug: "outdoor-living-spaces", title: "Outdoor Living Spaces", short: "Patios, exterior gathering areas, repairs, fencing, and improvements that make the outside more usable.", icon: Warehouse, focus: "patios, decks, fences, exterior gathering areas, repairs, access, shade, privacy, and usable outdoor upgrades", rooms: "patios, backyards, side yards, porches, deck areas, and exterior gathering spaces" },
  { slug: "repair-maintenance", title: "Repair & Maintenance", short: "Punch-list repairs, patching, painting, maintenance, and smaller details that keep a property sharp.", icon: Wrench, focus: "drywall patches, paint touchups, trim repairs, doors, hardware, exterior fixes, punch-list work, and property maintenance", rooms: "occupied homes, rental properties, offices, garages, kitchens, baths, and exterior areas" },
] as const;
const serviceSlugs = serviceDetails.map((service) => service.slug);
function slugifyService(title: string) { return title.toLowerCase().replace(/&/g, "and").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""); }
function serviceBySlug(slug?: string) { return serviceDetails.find((service) => service.slug === slug); }
function serviceSeoSections(service: typeof serviceDetails[number]) {
  const lower = service.title.toLowerCase();
  return [
    {
      heading: `${service.title} in Oklahoma City: start with the real condition of the home`,
      body: `Brothers Remodeling OKC handles ${lower} for homeowners who want practical remodeling help, not vague promises or a generic brochure answer. A good project starts by looking at what is already there: the age of the home, the condition of the surfaces, how the room is used, what has been repaired before, what needs to stay, what needs to change, and what level of finish makes sense for the budget. Many Oklahoma City homes have older framing, uneven floors, dated texture, old caulk lines, patched drywall, shifted trim, weather exposure, rental wear, or previous work that was done quickly. Those details matter because remodeling is never just the visible finish. The finish depends on prep, repair, installation, cleanup, and communication before the final coat of paint or last piece of trim goes in.`
    },
    {
      heading: `What ${lower} can include`,
      body: `For ${lower}, common work can include ${service.focus}. The exact scope depends on the home, the existing materials, the desired finish, and the way the project connects to nearby rooms or exterior areas. A kitchen update may involve cabinets, counters, backsplash, flooring, wall repair, lighting changes, appliance fit, and trim. A bathroom update may involve waterproofing, tile, fixtures, ventilation, drywall, vanity placement, flooring, and paint. Flooring work can affect baseboards, transitions, door clearance, and subfloor preparation. Exterior work can involve siding, trim, caulk, paint, doors, windows, deck details, fencing, and weather-facing repairs. Brothers Remodeling OKC keeps those connected details in one conversation so homeowners are not left coordinating unrelated pieces of the same finished result.`
    },
    {
      heading: `How to prepare before requesting a quote`,
      body: `The most useful first request includes the address area, the project type, photos if available, the room or exterior area involved, the approximate timeline, and a plain-English description of what is not working now. Homeowners do not need perfect measurements to start, but photos help show the existing condition, corners, transitions, access, ceiling height, flooring changes, water damage, trim gaps, patched areas, and other details that can affect the work. If the project involves ${service.rooms}, it helps to mention whether the home is occupied, whether pets are present, whether parking is limited, whether there are access restrictions, and whether the work needs to be phased around family schedules or tenants. Clear information helps Brothers Remodeling OKC decide whether the next step should be a call, a visit, a quote path, or a more detailed materials conversation.`
    },
    {
      heading: `A structured project path instead of guesswork`,
      body: `The project path is intentionally straightforward: receive the details, review the fit, confirm the next step, and then plan the work if the project makes sense. That structure is important because remodeling is a sequence of decisions. Before work begins, the homeowner and contractor should understand what area is being changed, what materials are expected, what preparation may be needed, how the new work meets existing surfaces, and what cleanup or finish details matter. During the project, small decisions can affect the final look: trim alignment, caulk lines, grout color, texture matching, flooring direction, thresholds, paint sheen, door swings, cabinet clearance, fixture height, and how old construction meets new material. Brothers Remodeling OKC focuses on direct communication so the homeowner understands the work being discussed before the project moves forward.`
    },
    {
      heading: `Why local Oklahoma City remodeling details matter`,
      body: `Oklahoma City homes are not all built the same. Some are older properties with original framing and settled floors. Some have storm exposure or exterior materials that need extra attention. Some have been updated several times by different owners. Some rental or investment properties need durable, clean work instead of delicate finishes. Local remodeling requires flexibility because hidden conditions can appear after old materials are removed. A wall that looked simple may have old patching behind it. Flooring may reveal subfloor movement. Exterior trim may show rot once paint is scraped. A bathroom may need more prep before tile can be installed correctly. Brothers Remodeling OKC does not need to invent big claims to explain that. The value is in careful observation, practical construction thinking, and honest next-step communication.`
    },
    {
      heading: `Materials, finishes, and realistic expectations`,
      body: `${service.title} can look very different depending on the finish level. A practical rental refresh, a mid-range family-home update, and a more detailed finish upgrade are not the same project even if they involve the same room. Materials affect cost, schedule, installation method, durability, and cleanup. Homeowners should think about whether they want simple and durable, clean and modern, or more detailed and custom. They should also consider how the project connects with nearby finishes. New flooring may make old trim look rough. New paint may expose wall texture problems. A new door may reveal framing that is not square. New exterior paint may show where caulking, trim, or siding repair is needed first. A clear conversation about finish expectations helps prevent a quote from being based on assumptions.`
    },
    {
      heading: `Communication in English or Spanish`,
      body: `Brothers Remodeling OKC welcomes English and Spanish project conversations. That matters because remodeling details need to be understood clearly. Homeowners should feel comfortable explaining what they want changed, asking what the next step is, and sharing concerns about timing, access, budget range, or finish level. A strong remodeling conversation is not only about selling the job. It is about understanding the home, the homeowner's priorities, and the practical steps required to complete the work. If project photos are available, sending them with the city or neighborhood, the room, and the desired result helps the team respond with better questions and a more useful next step.`
    },
    {
      heading: `Service area for this remodeling work`,
      body: `This ${lower} service is centered on Oklahoma City and nearby communities such as Edmond, Yukon, Moore, Midwest City, Del City, Bethany, Warr Acres, The Village, and Nichols Hills. Projects outside the core area can still be reviewed by work type, schedule, access, and fit. The goal is not to promise every project in every location. The goal is to review the request honestly and decide whether Brothers Remodeling OKC is the right fit for the work. Larger or clearer projects are easier to evaluate than vague requests with no photos, no city, and no description. Homeowners can improve the first response by sharing enough context to understand the scope.`
    },
    {
      heading: `What this page is meant to do`,
      body: `This page is written to help homeowners understand ${lower} before reaching out. It avoids fake review counts, invented awards, fake license numbers, and generic claims that do not help with a real project. Instead, it explains how Brothers Remodeling OKC thinks about the service, what details are useful, how the work may connect to other parts of the home, and how to begin the quote conversation. If you are comparing remodeling options, use this page as a checklist. Describe the room or exterior area. Gather photos. Note the city or neighborhood. Think about the desired finish level. Mention your timeline. Then send enough detail for a useful response.`
    },
    {
      heading: `Requesting a ${lower} quote`,
      body: `When you are ready to discuss ${lower}, use the contact form or email project photos directly to Brothers Remodeling OKC. Include the project type, the address area, the rooms or exterior areas involved, and what you want the finished result to accomplish. A clear request helps the team respond with better questions and a better next step. Whether the project is a focused update, a repair-heavy improvement, or part of a larger whole-home plan, the goal is the same: practical remodeling work, direct communication, and a finished space that makes the home look better and work better for everyday life.`
    }
  ];
}
function serviceSeoCopy(title: string) { const detail = serviceDetails.find((service) => service.title === title) || serviceDetails[0]; return serviceSeoSections(detail).map((section) => section.body); }

const cities: City[] = [
  { name: "Oklahoma City", slug: "oklahoma-city", note: "kitchen remodels, bathroom upgrades, flooring, drywall, trim, paint, exterior repairs, garage updates, and full-home refreshes for OKC homeowners", nearby: "Downtown, Uptown, Classen, Mayfair, Belle Isle, Capitol Hill, and central OKC neighborhoods" },
  { name: "Edmond", slug: "edmond", note: "kitchen and bath updates, trim carpentry, flooring, painting, exterior improvements, and careful finish work for north metro homes", nearby: "Edmond, Memorial Road, north OKC, and nearby neighborhoods that need clean, practical remodeling" },
  { name: "Yukon", slug: "yukon", note: "west-metro remodels including kitchens, bathrooms, floors, drywall, exterior repairs, garages, and whole-home updates", nearby: "Yukon, Lake Overholser, west OKC, and nearby Canadian County homes" },
  { name: "Nichols Hills", slug: "nichols-hills", note: "premium interior finishes, kitchens, bathrooms, exterior details, trim, doors, and careful home upgrades", nearby: "Nichols Hills, Grand Boulevard, Wilshire, and nearby northwest OKC homes" },
  { name: "The Village", slug: "the-village", note: "bathroom remodels, kitchen updates, flooring, paint, doors, trim, and practical repairs for established homes", nearby: "The Village, Britton, Casady, and nearby north OKC streets" },
  { name: "Warr Acres", slug: "warr-acres", note: "whole-home refreshes, flooring, drywall, paint, garage improvements, exterior repair, and maintenance work", nearby: "Warr Acres, Putnam City, Bethany edge, and northwest OKC homes" },
  { name: "Bethany", slug: "bethany", note: "kitchens, baths, additions, flooring, exterior paint, window and door updates, and repair projects", nearby: "Bethany, Lake Overholser edge, Route 66 corridor, and west OKC homes" },
  { name: "Del City", slug: "del-city", note: "interior remodels, exterior updates, doors, windows, flooring, paint, and repair work", nearby: "Del City, Sunnylane corridor, Tinker-area neighborhoods, and southeast OKC edge" },
  { name: "Midwest City", slug: "midwest-city", note: "kitchen updates, bathroom renovations, flooring, drywall, garages, exterior work, and general remodeling", nearby: "Midwest City, Tinker-area homes, Soldier Creek, and nearby east-side communities" },
  { name: "Moore", slug: "moore", note: "nearby remodel projects for kitchens, bathrooms, floors, exterior repairs, paint, and full-home updates", nearby: "Moore, north Moore, south OKC edge, and I-35 corridor homes" },
];

function track(type: string, payload: Record<string, string> = {}) { try { window.dispatchEvent(new CustomEvent("jeriko:track", { detail: { type, ...payload } })); } catch {} }
function AppLink({ href, children, className, onClick }: { href: string; children: React.ReactNode; className?: string; onClick?: () => void }) { return <Link href={href} className={className} onClick={onClick}>{children}</Link>; }
function cityBySlug(slug?: string) { return cities.find((city) => city.slug === slug); }

function Header() { return <header className="top"><AppLink className="brand" href="/"><img src="/images/current-site/logo.jpg" alt="Brothers Remodeling OKC logo" /><b>Brothers Remodeling OKC</b></AppLink><nav aria-label="Main navigation"><AppLink href="/">Home</AppLink><AppLink href="/services">Services</AppLink><AppLink href="/process">Process</AppLink><AppLink href="/about">About</AppLink><AppLink href="/gallery">Gallery</AppLink><AppLink href="/service-area">Service Area</AppLink><AppLink href="/contact">Contact</AppLink></nav><AppLink className="pill" href="/contact">Request Quote</AppLink></header>; }
function Footer() { return <footer><b>Brothers Remodeling OKC LLC</b><span>Full-service bilingual remodeling in Oklahoma City, OK.</span><AppLink href="/services">Services</AppLink><AppLink href="/process">Process</AppLink><AppLink href="/service-area">Service Area</AppLink><AppLink href="/contact">Request Quote</AppLink></footer>; }
function Shell({ children }: { children: React.ReactNode }) { return <><Header /><main>{children}</main><StickyAuditRail /><Footer /></>; }

function LeadForm({ city }: { city?: string }) {
  const [status, setStatus] = React.useState<"idle" | "sending" | "sent" | "error">("idle");
  const [message, setMessage] = React.useState("");
  async function submit(e: React.FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const form = e.currentTarget;
    const data = new FormData(form);
    const fullName = String(data.get("name") || "").trim();
    const phone = String(data.get("phone") || "").trim();
    const projectType = String(data.get("project") || "").trim();
    const projectDescription = String(data.get("message") || "").trim();
    if (!fullName || !phone || !projectType || !projectDescription) {
      setStatus("error");
      setMessage("Please add your name, phone, project type, and a short project description before sending.");
      return;
    }
    const [firstName, ...rest] = fullName.split(/\s+/);
    const payload = {
      firstName: firstName || "Homeowner",
      lastName: rest.join(" ") || "Not provided",
      email: String(data.get("email") || email),
      phone,
      city: String(data.get("city") || city || "Oklahoma City"),
      state: "Oklahoma",
      projectType,
      projectDescription,
      bestTime: String(data.get("bestTime") || "Not specified"),
      sourceUrl: window.location.href,
      sourceLabel: city ? "city-page" : "website",
    };
    setStatus("sending");
    track("form_submit", { form: city ? "city-page" : "main" });
    try {
      const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      if (!response.ok) throw new Error("Contact endpoint rejected the request");
      setStatus("sent");
      setMessage("Your project details were sent. Brothers Remodeling OKC will review the request and follow up with the next step.");
      form.reset();
    } catch {
      setStatus("error");
      setMessage(`The form could not be sent right now. Please email the project details and photos to ${email}.`);
    }
  }
  return <form data-jeriko-track="form_submit" className="lead" onSubmit={submit} noValidate><h3>Request a remodeling quote</h3><p>Tell us about the project. English or Spanish is welcome.</p>{message && <div className={`formStatus ${status}`} role="status"><b>{status === "sent" ? "Request sent." : "Email option available."}</b><span>{message}</span></div>}<input name="name" autoComplete="name" required placeholder="Name / Nombre" /><input name="phone" type="tel" autoComplete="tel" required placeholder="Phone / Teléfono" /><input name="email" type="email" autoComplete="email" placeholder="Email" /><input name="city" defaultValue={city || ""} placeholder="City / Area" /><select name="project" required><option value="">Project type</option><option>Kitchen</option><option>Bathroom</option><option>Flooring</option><option>Addition</option><option>Deck</option><option>Whole Home</option><option>Exterior</option><option>Other</option></select><textarea name="message" required placeholder="What do you want remodeled? Kitchen, bathroom, floors, paint, exterior, garage, whole home..." /><input name="bestTime" placeholder="Best time to call" /><button disabled={status === "sending"}>{status === "sending" ? "Sending..." : "Send My Project"} <ArrowRight size={18} /></button><small>You can also send photos and details to <a href={`mailto:${email}`}>{email}</a>.</small></form>;
}

function ServicesGrid() { return <div className="cards">{services.map(([title, text, Icon]) => <article className="card" key={title}><Icon size={34} /><h3>{title}</h3><p>{text}</p></article>)}</div>; }
function LeadOpsVisual() { return <div className="opsVisual" aria-label="Remodel project command center visual"><div className="opsTop"><span>Project path</span><b>Project Details → Visit → Quote → Build</b></div><div className="opsRows"><span className="active">Kitchen / bath requests</span><span>Photos and access notes</span><span>Materials and finish level</span><span>Scheduling and next steps</span></div><div className="opsMeter"><i style={{ width: "76%" }} /></div></div>; }
function LeadFlowLineSection() { const steps = ["Project details received", "Details reviewed", "Visit or quote step confirmed", "Remodel work scheduled"]; return <section className="section flow"><p className="eyebrow dark"><ClipboardCheck size={18} /> Project flow</p><h2>A cleaner path from first message to remodel plan.</h2><div className="flowLine">{steps.map((step, index) => <div key={step} className="flowStep"><b>{index + 1}</b><span>{step}</span></div>)}</div></section>; }
function LeadLeakAudit() { const items = ["Room or area is clearly described", "Photos are ready to send", "Timeline expectations are known", "Access, pets, parking, or special notes are listed", "Budget range or finish level can be discussed"]; const [checked, setChecked] = React.useState<string[]>([]); return <section className="section audit"><p className="eyebrow dark"><Shield size={18} /> Interactive checklist</p><h2>Before you request a quote, collect the details that prevent back-and-forth.</h2><div className="auditGrid">{items.map((item) => <label key={item}><input type="checkbox" checked={checked.includes(item)} onChange={(e) => setChecked((current) => e.target.checked ? [...current, item] : current.filter((x) => x !== item))} /><span>{item}</span></label>)}</div><p className="sectionLead">Checklist progress: {checked.length} of {items.length} ready.</p></section>; }
function BeforeAfterComparison() { return <section className="section compare"><p className="eyebrow dark"><Paintbrush size={18} /> Before / after comparison</p><h2>From scattered remodel ideas to a clear project conversation.</h2><div className="compareGrid"><article><b>Before</b><p>Loose ideas, missing photos, unclear priorities, unknown timeline, and no easy way to explain the remodel.</p></article><article><b>After</b><p>Room, photos, timeline, city, and project type collected so Brothers Remodeling OKC can respond with a useful next step.</p></article></div></section>; }
function StickyAuditRail() { return <aside className="stickyRail"><span>Ready for a remodel?</span><AppLink href="/contact">Request quote</AppLink></aside>; }

function HomePage() { return <Shell><section className="hero"><div className="glow one" /><div className="glow two" /><div className="heroGrid"><div><p className="eyebrow"><Sparkles size={18} /> Full-service remodeling • English / Español</p><h1>Remodel your OKC home without the runaround.</h1><p className="sub">Brothers Remodeling OKC LLC helps homeowners update kitchens, bathrooms, floors, walls, exterior spaces, garages, and full homes across Oklahoma City and nearby areas.</p><div className="actions"><AppLink className="cta" href="/contact">Request Remodeling Quote <ArrowRight size={20} /></AppLink><a data-jeriko-track="email_click" onClick={() => track("email_click", { location: "hero" })} className="ghost" href={`mailto:${email}`}>Email Project Photos</a></div><div className="stats"><span><b>Full</b> service</span><span><b>Bi</b> lingual</span><span><b>OKC</b> focused</span></div></div><div className="showcase"><img src="/images/current-site/hero.jpg" alt="Brothers Remodeling OKC exterior remodeling work" /><div className="glass">Kitchens • Bathrooms • Floors • Paint • Exterior • Repairs</div></div></div></section><section className="section commandWrap"><LeadOpsVisual /></section><section className="strip">{["English and Spanish communication available", "Kitchens, baths, floors, paint, exterior work, garages, and repairs", "Focused on Oklahoma City and nearby communities", "Direct remodeling communication"].map((x) => <span key={x}><CheckCircle2 size={18} />{x}</span>)}</section><section className="section"><p className="eyebrow dark"><Hammer size={18} /> Remodeling services</p><h2>One remodeling company for almost every part of the home.</h2><ServicesGrid /></section><LeadFlowLineSection /><LeadLeakAudit /><BeforeAfterComparison /><ServiceAreaSection /></Shell>; }
function ServicesPage() { return <Shell><PageHero icon={<Hammer size={18} />} eyebrow="Remodeling services" title="Kitchen, bathroom, interior, exterior, flooring, paint, and repair remodeling in OKC." text="Brothers Remodeling OKC gives homeowners one place to start for the most common remodeling needs around the home." /><section className="section"><div className="cards">{services.map(([title, text, Icon]) => <AppLink className="card serviceLinkCard" href={`/services/${slugifyService(title)}`} key={title}><Icon size={34} /><h3>{title}</h3><p>{text}</p><span>Read the {title.toLowerCase()} service page <ArrowRight size={16} /></span></AppLink>)}</div></section><LeadFlowLineSection /></Shell>; }
function ServiceDetailPage({ params }: { params: { serviceSlug: string } }) {
  const [location] = useLocation();
  const fallbackSlug = location.split("/services/")[1]?.split("/")[0];
  const service = serviceBySlug(params.serviceSlug || fallbackSlug);
  if (!service) return <NotFound />;
  const Icon = service.icon;
  const sections = serviceSeoSections(service);
  return <Shell><PageHero icon={<Icon size={18} />} eyebrow="Remodeling service" title={`${service.title} in Oklahoma City`} text={service.short} /><section className="section serviceSeoPage"><div><p className="eyebrow dark"><Hammer size={18} /> Detailed service guidance</p><h2>What homeowners should know before starting {service.title.toLowerCase()}.</h2>{sections.map((section) => <article className="seoArticleBlock" key={section.heading}><h3>{section.heading}</h3><p>{section.body}</p></article>)}<h3>Common {service.title.toLowerCase()} details</h3><ul>{["Existing condition and repair needs", "Material and finish expectations", "Schedule, access, and cleanup notes", "Related drywall, paint, trim, floor, door, or exterior tie-ins", "Photos, measurements, and address-area details for the quote conversation"].map((item) => <li key={item}><CheckCircle2 size={18} /> {item}</li>)}</ul></div><LeadForm /></section><LeadLeakAudit /><BeforeAfterComparison /></Shell>;
}
function ProcessPage() { return <Shell><PageHero icon={<Shield size={18} />} eyebrow="Process" title="A clear remodeling process before work begins." text="The goal is direct communication, realistic scope conversations, and a next step homeowners understand." /><section className="split"><div><h2>How the project path works</h2><ul>{[["Send details", "Share the room, city, photos, timeline, and what needs to change."], ["Check scope", "Brothers Remodeling OKC reviews the work type, access, materials, and schedule."], ["Confirm next step", "If the job is a good match, the team follows up with the visit, quote step, or project conversation."], ["Build with updates", "Work proceeds with clear communication in English or Spanish."]].map(([title, text]) => <li key={title}><CheckCircle2 /><span><b>{title}</b><br />{text}</span></li>)}</ul></div><LeadOpsVisual /></section><LeadLeakAudit /></Shell>; }
function AboutPage() { return <Shell><PageHero icon={<Building2 size={18} />} eyebrow="About" title="Brothers Remodeling OKC is a local remodeling contractor for real home upgrades." text="The company focuses on practical, good-looking remodel work across kitchens, bathrooms, flooring, interiors, exterior improvements, garages, repairs, and whole-home updates." /><section className="section"><h2>Built for homeowners who want direct remodeling help.</h2><p className="sectionLead">Brothers Remodeling OKC presents services, service area, process, and quote options plainly, without invented credentials or exaggerated claims.</p><div className="cards"><article className="card"><Languages /><h3>Bilingual communication</h3><p>English and Spanish project conversations are welcome.</p></article><article className="card"><Wrench /><h3>Wide service range</h3><p>Multiple rooms and repair scopes can be discussed in one place.</p></article><article className="card"><MapPin /><h3>OKC area focus</h3><p>Oklahoma City and nearby communities are the primary service area.</p></article></div></section></Shell>; }
function GalleryPage() { return <Shell><PageHero icon={<Paintbrush size={18} />} eyebrow="Gallery" title="Project inspiration for kitchens, baths, interiors, and exterior updates." text="Use these remodeling categories to show Brothers Remodeling OKC what kind of finish, room, or repair you want quoted." /><section className="section portfolio"><div className="portfolioGrid"><article className="portfolioCard featured"><div className="portfolioNoImage exteriorProof"><Paintbrush size={46} /><span>Exterior updates, curb appeal, repairs, doors, windows, paint, and outdoor spaces</span></div><div><h3>Exterior and curb appeal work</h3><p>Exterior updates, repair scopes, paint, fencing, doors, windows, and curb-appeal improvements for homes that need a sharper first impression.</p></div></article><article className="portfolioCard featured"><div className="portfolioNoImage interiorProof"><Hammer size={46} /><span>Interior finishes, drywall, trim, flooring, paint, kitchens, and baths</span></div><div><h3>Interior remodel finish work</h3><p>Interior improvements, finish details, and room-by-room upgrades that make the home cleaner, more useful, and easier to live in.</p></div></article><article className="portfolioCard"><div className="portfolioNoImage"><Hammer size={46} /><span>Kitchen • bath • flooring • paint • exterior • garage • repairs</span></div><div><h3>Remodeling categories</h3><p>Kitchen, bath, flooring, paint, exterior, garage, and repair scopes are organized so homeowners can start a clear quote conversation.</p></div></article></div></section><BeforeAfterComparison /></Shell>; }
function ServiceAreaSection() { return <section className="section area"><p className="eyebrow dark"><MapPin size={18} /> Service area</p><h2>Remodeling help centered on Oklahoma City.</h2><p className="sectionLead">Brothers Remodeling OKC focuses on the core Oklahoma City metro first: kitchens, bathrooms, flooring, paint, exterior repairs, garages, additions, and whole-home updates. Nearby communities are reviewed by project fit, access, timing, and work type.</p><div className="areaGrid"><div><h3>Primary OKC-area communities</h3><p>Use the city links below to describe where the home is and what kind of remodeling help you need.</p><div className="chips">{cities.map((z) => <AppLink key={z.slug} href={`/service-area/${z.slug}`}>{z.name}</AppLink>)}</div></div><div className="serviceMapVisual" role="img" aria-label="Oklahoma City centered service area visual"><b>OKC</b><span>Core metro first. Nearby communities reviewed by project type, access, schedule, and fit.</span></div></div></section>; }
function ServiceAreaPage() { return <Shell><PageHero icon={<MapPin size={18} />} eyebrow="Local remodeling service area" title="Kitchen, bathroom, interior, exterior, and repair remodeling near Oklahoma City." text="Brothers Remodeling OKC serves Oklahoma City and nearby surrounding communities with bilingual remodeling communication and a practical quote path." /><ServiceAreaSection /><section className="section"><h2>What service-area fit means.</h2><div className="cards"><article className="card"><MapPin /><h3>Location</h3><p>Start with the city or nearest OKC-area community so the team can review drive time and access.</p></article><article className="card"><Hammer /><h3>Scope</h3><p>Larger remodels, kitchens, bathrooms, flooring, exterior work, and multi-room updates are easier to plan than vague repair requests.</p></article><article className="card"><ClipboardCheck /><h3>Details</h3><p>Photos, room notes, timing, and finish expectations help Brothers Remodeling OKC respond with the right next step.</p></article><article className="card"><Languages /><h3>Communication</h3><p>English and Spanish project conversations are welcome for homeowners across the OKC area.</p></article></div></section></Shell>; }
function CityPage({ params }: { params: { citySlug: string } }) { const city = cityBySlug(params.citySlug); if (!city) return <NotFound />; const featured = services.slice(0, 6); const article = /^[AEIOU]/i.test(city.name) ? "an" : "a"; return <Shell><PageHero icon={<MapPin size={18} />} eyebrow={`${city.name} remodeling contractor`} title={`${city.name} remodeling services for practical home upgrades.`} text={`Brothers Remodeling OKC helps homeowners in and around ${city.name} start kitchen, bathroom, flooring, interior, exterior, garage, and repair projects with clear bilingual communication.`} /><section className="section citySeo"><div><h2>Home remodeling in {city.name}</h2><p>Common requests around {city.name} include {city.note}. Nearby focus areas include {city.nearby}.</p><p>Good quote requests include the room or exterior area, photos if available, the problem you want solved, timing, and whether the project involves materials, access limitations, or multiple rooms.</p><div className="cityDetailGrid"><article><b>Best fit projects</b><span>Kitchens, baths, flooring, paint, drywall, trim, doors, exterior repairs, garages, additions, and whole-home refreshes.</span></article><article><b>Helpful first details</b><span>Address area, photos, room size, desired finish level, timeline, and whether you need English or Spanish communication.</span></article></div></div><div className="seoBox"><h3>Services for {city.name}</h3><ul>{featured.map(([item]) => <li key={item}><CheckCircle2 size={18} /> {item}</li>)}</ul></div></section><section className="section"><h2>How Brothers reviews {article} {city.name} remodel request.</h2><div className="flowLine">{["Confirm city and project type", "Review photos and scope", "Discuss quote or visit step", "Plan schedule and work details"].map((step, index) => <div key={step} className="flowStep"><b>{index + 1}</b><span>{step}</span></div>)}</div></section><section className="contact" id="quote"><div><h2>Request a remodeling quote in {city.name}.</h2><p>Tell Brothers Remodeling OKC what you want changed, what area the home is in, and whether you have project photos. The more specific the request, the faster the team can decide the right next step.</p><p className="contactLine"><Mail /> <a href={`mailto:${email}`}>{email}</a></p></div><LeadForm city={city.name} /></section></Shell>; }
function ContactPage() { return <Shell><PageHero icon={<Mail size={18} />} eyebrow="Contact Brothers Remodeling OKC" title="Tell us what you want remodeled." text="Send project details in English or Spanish. Include the room, address area, timeline, and photos if you have them." /><section className="contact"><div><h2>Request a quote conversation.</h2><p>Brothers Remodeling OKC handles kitchens, bathrooms, flooring, interior renovations, exterior remodeling, garages, repairs, commercial spaces, and whole-home updates in the Oklahoma City area.</p><p className="contactLine"><Mail /> <a data-jeriko-track="email_click" href={`mailto:${email}`}>{email}</a></p><p className="contactLine"><Phone /> Use the form or email project photos to start a real quote conversation.</p></div><LeadForm /></section></Shell>; }
function PageHero({ eyebrow, title, text, icon }: { eyebrow: string; title: string; text: string; icon: React.ReactNode }) { return <section className="pageHero"><p className="eyebrow">{icon} {eyebrow}</p><h1>{title}</h1><p>{text}</p></section>; }
function NotFound() { const [, navigate] = useLocation(); return <Shell><section className="pageHero"><h1>Page not found</h1><p>The page you requested is not available.</p><button className="cta" onClick={() => navigate("/")}>Back home</button></section></Shell>; }

export default function App() { return <Switch><Route path="/" component={HomePage} /><Route path="/services" component={ServicesPage} /><Route path="/services/kitchen-remodeling" component={ServiceDetailPage} /><Route path="/services/bathroom-remodeling" component={ServiceDetailPage} /><Route path="/services/interior-renovations" component={ServiceDetailPage} /><Route path="/services/flooring-installation" component={ServiceDetailPage} /><Route path="/services/exterior-remodeling" component={ServiceDetailPage} /><Route path="/services/additions-garages-conversions" component={ServiceDetailPage} /><Route path="/services/outdoor-living-spaces" component={ServiceDetailPage} /><Route path="/services/repair-maintenance" component={ServiceDetailPage} /><Route path="/services/:serviceSlug" component={ServiceDetailPage} /><Route path="/process" component={ProcessPage} /><Route path="/about" component={AboutPage} /><Route path="/gallery" component={GalleryPage} /><Route path="/service-area" component={ServiceAreaPage} /><Route path="/service-area/:citySlug" component={CityPage} /><Route path="/contact" component={ContactPage} /><Route component={NotFound} /></Switch>; }
