import express from 'express';
import path from 'path';
import { fileURLToPath } from 'url';
const app = express();
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.resolve(__dirname, 'public');
app.get('/api/health', (_req, res) => res.json({ ok: true, app: 'brothers-remodeling-okc' }));
app.use(express.static(publicDir));
app.get('*', (_req, res) => res.sendFile(path.join(publicDir, 'index.html')));
const port = Number(process.env.PORT || 4173);
app.listen(port, '0.0.0.0', () => console.log(`Brothers Remodeling OKC running on ${port}`));
