import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
const dist = 'dist/public';
const siteUrl = (process.env.SITE_URL || 'https://brothers-remodeling-okc.vercel.app').replace(/\/$/, '');
const cityContent = JSON.parse(readFileSync('client/src/data/cityContent.json', 'utf8'));
function esc(value){ return String(value).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }
const cities = [
  ['oklahoma-city','Oklahoma City','kitchen remodels, bathroom upgrades, flooring, drywall, trim, paint, exterior repairs, garage updates, and full-home refreshes for OKC homeowners'],
  ['edmond','Edmond','kitchen and bath updates, trim carpentry, flooring, painting, exterior improvements, and careful finish work for north metro homes'],
  ['yukon','Yukon','west-metro remodels including kitchens, bathrooms, floors, drywall, exterior repairs, garages, and whole-home updates'],
  ['nichols-hills','Nichols Hills','premium interior finishes, kitchens, bathrooms, exterior details, trim, doors, and careful home upgrades'],
  ['the-village','The Village','bathroom remodels, kitchen updates, flooring, paint, doors, trim, and practical repairs for established homes'],
  ['warr-acres','Warr Acres','whole-home refreshes, flooring, drywall, paint, garage improvements, exterior repair, and maintenance work'],
  ['bethany','Bethany','kitchens, baths, additions, flooring, exterior paint, window and door updates, and repair projects'],
  ['del-city','Del City','interior remodels, exterior updates, doors, windows, flooring, paint, and repair work'],
  ['midwest-city','Midwest City','kitchen updates, bathroom renovations, flooring, drywall, garages, exterior work, and general remodeling'],
  ['moore','Moore','nearby remodel projects for kitchens, bathrooms, floors, exterior repairs, paint, and full-home updates'],
];
const services = [
  ['kitchen-remodeling','Kitchen Remodeling','cabinet layout, countertops, backsplash, lighting, flooring, appliance placement, storage, and daily kitchen flow','kitchens, dining edges, pantry areas, laundry connections, and open living spaces'],
  ['bathroom-remodeling','Bathroom Remodeling','showers, tubs, tile, vanities, waterproofing, ventilation, storage, fixture placement, and clean finish details','primary baths, hall baths, powder rooms, guest baths, and compact bathrooms'],
  ['interior-renovations','Interior Renovations','drywall, texture, trim, paint, doors, baseboards, room openings, accent details, and layout improvements','living rooms, bedrooms, hallways, offices, rental spaces, and whole-home interiors'],
  ['flooring-installation','Flooring Installation','floor removal, subfloor prep, LVP, laminate, tile, transitions, baseboards, and finish carpentry','kitchens, baths, living rooms, bedrooms, hallways, garages, and rental properties'],
  ['exterior-remodeling','Exterior Remodeling','siding, trim, paint, doors, windows, decks, fences, exterior repairs, curb appeal, and weather-facing details','front elevations, patios, side yards, backyards, garages, entries, and rental exteriors'],
  ['additions-garages-conversions','Additions, Garages & Conversions','added square footage, garage conversions, office spaces, storage, framing, insulation, drywall, flooring, and finish tie-ins','garages, bonus rooms, additions, offices, workshops, and light commercial spaces'],
  ['outdoor-living-spaces','Outdoor Living Spaces','patios, decks, fences, exterior gathering areas, repairs, access, shade, privacy, and usable outdoor upgrades','patios, backyards, side yards, porches, deck areas, and exterior gathering spaces'],
  ['repair-maintenance','Repair & Maintenance','drywall patches, paint touchups, trim repairs, doors, hardware, exterior fixes, punch-list work, and property maintenance','occupied homes, rental properties, offices, garages, kitchens, baths, and exterior areas'],
];
const baseRoutes = [
  ['/', 'Brothers Remodeling OKC LLC | Full-Service Remodeling in Oklahoma City', 'Bilingual full-service remodeling for Oklahoma City homeowners: kitchens, bathrooms, flooring, paint, exterior work, garages, repairs, and whole-home updates.'],
  ['/services', 'Remodeling Services in OKC | Brothers Remodeling OKC', 'Kitchen, bathroom, interior, exterior, flooring, drywall, paint, garage, addition, and repair remodeling services in Oklahoma City.'],
  ['/process', 'Remodeling Process in OKC | Brothers Remodeling OKC', 'How Brothers Remodeling OKC moves from project details to visit, quote, scheduling, and remodeling work.'],
  ['/about', 'About Brothers Remodeling OKC | Local Remodeling Contractor', 'Learn about Brothers Remodeling OKC, a bilingual local remodeling contractor serving Oklahoma City homeowners.'],
  ['/service-area', 'Oklahoma City Remodeling Service Area | Brothers Remodeling OKC', 'Brothers Remodeling OKC serves Oklahoma City and nearby communities with bilingual full-service remodeling.'],
  ['/gallery', 'Remodeling Gallery | Brothers Remodeling OKC', 'Kitchen, bath, interior, exterior, flooring, paint, garage, and repair remodeling categories for Brothers Remodeling OKC homeowners.'],
  ['/contact', 'Request a Remodeling Quote | Brothers Remodeling OKC', 'Contact Brothers Remodeling OKC for bilingual remodeling quote conversations in the Oklahoma City area.'],
];
const cityRoutes = cities.map(([slug,name,note]) => [`/service-area/${slug}`, `${name} Remodeling Services | Brothers Remodeling OKC`, `Bilingual remodeling services near ${name}: ${note}. Request a kitchen, bath, flooring, paint, exterior, garage, or repair quote.`]);
const serviceRoutes = services.map(([slug,title,focus]) => [`/services/${slug}`, `${title} in Oklahoma City | Brothers Remodeling OKC`, `${title} for Oklahoma City homes with bilingual communication, practical project review, and remodeling details including ${focus}.`]);
const routes = [...baseRoutes, ...serviceRoutes, ...cityRoutes];
function serviceBody(slug,name,focus,rooms){
  const lower = name.toLowerCase();
  const sections = [
    [`${name} in Oklahoma City starts with the real condition of the home`, `Brothers Remodeling OKC handles ${lower} for homeowners who want practical remodeling help, not vague promises or a thin service page. A useful project conversation starts with what is already there: the age of the home, the condition of the surfaces, how the room is used, what has been repaired before, what must stay, what must change, and what finish level makes sense for the budget. Many Oklahoma City homes have older framing, uneven floors, dated texture, old caulk lines, patched drywall, shifted trim, weather exposure, rental wear, or previous work that was done quickly. Those details matter because remodeling is never only the visible finish. The finish depends on prep, repair, installation, cleanup, and communication before the final coat of paint, last tile line, or final piece of trim goes in.`],
    [`What ${lower} can include`, `For ${lower}, common work can include ${focus}. The exact scope depends on the home, the existing materials, the desired finish, and the way the project connects to nearby rooms or exterior areas. Brothers Remodeling OKC keeps connected details in one conversation so homeowners are not left coordinating unrelated pieces of the same finished result. Floors may affect baseboards and transitions. Paint may reveal drywall issues. Exterior work may expose trim or siding repair. A focused service request can still touch several parts of the house, which is why the first conversation should be clear and complete.`],
    [`How to prepare before requesting a quote`, `The most useful first request includes the address area, the project type, photos if available, the room or exterior area involved, the approximate timeline, and a plain-English description of what is not working now. Homeowners do not need perfect measurements to start, but photos help show the existing condition, corners, transitions, access, ceiling height, flooring changes, water damage, trim gaps, patched areas, and other details that can affect the work. If the project involves ${rooms}, it helps to mention whether the home is occupied, whether pets are present, whether parking is limited, whether there are access restrictions, and whether the work needs to be phased around family schedules or tenants.`],
    [`A structured project path instead of guesswork`, `The project path is intentionally straightforward: receive the details, review the fit, confirm the next step, and then plan the work if the project makes sense. That structure is important because remodeling is a sequence of decisions. Before work begins, the homeowner and contractor should understand what area is being changed, what materials are expected, what preparation may be needed, how the new work meets existing surfaces, and what cleanup or finish details matter. During the project, small decisions can affect the final look, including trim alignment, caulk lines, grout color, texture matching, flooring direction, thresholds, paint sheen, door swings, cabinet clearance, fixture height, and how old construction meets new material.`],
    [`Why local Oklahoma City remodeling details matter`, `Oklahoma City homes are not all built the same. Some are older properties with original framing and settled floors. Some have storm exposure or exterior materials that need extra attention. Some have been updated several times by different owners. Some rental or investment properties need durable, clean work instead of delicate finishes. Local remodeling requires flexibility because hidden conditions can appear after old materials are removed. A wall that looked simple may have old patching behind it. Flooring may reveal subfloor movement. Exterior trim may show rot once paint is scraped. A bathroom may need more prep before tile can be installed correctly.`],
    [`Materials, finishes, and realistic expectations`, `${name} can look very different depending on the finish level. A practical rental refresh, a mid-range family-home update, and a more detailed finish upgrade are not the same project even if they involve the same room. Materials affect cost, schedule, installation method, durability, and cleanup. Homeowners should think about whether they want simple and durable, clean and modern, or more detailed and custom. They should also consider how the project connects with nearby finishes. New flooring may make old trim look rough. New paint may expose wall texture problems. A new door may reveal framing that is not square. A clear conversation about finish expectations helps prevent a quote from being based on assumptions.`],
    [`Communication in English or Spanish`, `Brothers Remodeling OKC welcomes English and Spanish project conversations. That matters because remodeling details need to be understood clearly. Homeowners should feel comfortable explaining what they want changed, asking what the next step is, and sharing concerns about timing, access, budget range, or finish level. A strong remodeling conversation is not only about selling the job. It is about understanding the home, the homeowner's priorities, and the practical steps required to complete the work. If project photos are available, sending them with the city or neighborhood, the room, and the desired result helps the team respond with better questions and a more useful next step.`],
    [`Service area for this remodeling work`, `This ${lower} service is centered on Oklahoma City and nearby communities such as Edmond, Yukon, Moore, Midwest City, Del City, Bethany, Warr Acres, The Village, and Nichols Hills. Projects outside the core area can still be reviewed by work type, schedule, access, and fit. The goal is not to promise every project in every location. The goal is to review the request honestly and decide whether Brothers Remodeling OKC is the right fit for the work. Larger or clearer projects are easier to evaluate than vague requests with no photos, no city, and no description.`],
    [`Requesting a ${lower} quote`, `When you are ready to discuss ${lower}, use the contact form or email project photos directly to Brothers Remodeling OKC. Include the project type, the address area, the rooms or exterior areas involved, and what you want the finished result to accomplish. A clear request helps the team respond with better questions and a better next step. Whether the project is a focused update, a repair-heavy improvement, or part of a larger whole-home plan, the goal is the same: practical remodeling work, direct communication, and a finished space that makes the home look better and work better for everyday life.`],
  ];
  return `<main data-jeriko-prerender="true"><section><p>Remodeling service • English / Español</p><h1>${esc(name)} in Oklahoma City</h1><p>Brothers Remodeling OKC helps homeowners with ${esc(lower)} that is practical, clear, and connected to the rest of the home.</p>${sections.map(([heading,body])=>`<article><h2>${esc(heading)}</h2><p>${esc(body)}</p></article>`).join('')}<h2>Common ${esc(lower)} details</h2><ul><li>Existing condition and repair needs</li><li>Material and finish expectations</li><li>Schedule, access, and cleanup notes</li><li>Related drywall, paint, trim, floor, door, or exterior tie-ins</li><li>Photos, measurements, and address-area details for the quote conversation</li></ul><p><a href="/contact">Request a ${esc(lower)} quote</a> or <a href="mailto:brothersremodelingokc@gmail.com" data-jeriko-track="email_click">email project photos</a>.</p><form action="/api/contact" method="post" data-jeriko-track="form_submit" aria-label="${esc(name)} quote request"><input name="name" autocomplete="name" required /><input name="phone" type="tel" autocomplete="tel" required /><input name="project" value="${esc(name)}" /><textarea name="message" required></textarea><button type="submit">Request quote</button></form></section></main>`;
}
function bodyFor(path){
  const service = services.find(([slug]) => path === `/services/${slug}`);
  if(service){return serviceBody(...service)}
  const city = cities.find(([slug]) => path === `/service-area/${slug}`);
  if(city){const [slug,name,note]=city;const copy=cityContent[slug];const paragraphs=(copy?.paragraphs||[]).map((paragraph)=>`<p>${esc(paragraph)}</p>`).join('');return `<main data-jeriko-prerender="true"><section><p>Full-service bilingual remodeling near ${name}.</p><h1>${name} remodeling services for homeowners</h1><p>Brothers Remodeling OKC helps homeowners around ${name} with kitchen remodeling, bathroom remodeling, flooring, drywall, painting, exterior repairs, doors, windows, garages, and whole-home updates.</p><p>Common requests include ${note}. English and Spanish communication is available.</p><section class="cityLongCopy"><h2>${name} remodeling guidance for real homeowner decisions</h2>${paragraphs}</section><p><a href="/contact">Request a ${name} remodeling quote</a> or <a href="mailto:brothersremodelingokc@gmail.com" data-jeriko-track="email_click">email project photos</a>.</p><form action="/api/contact" method="post" data-jeriko-track="form_submit" aria-label="${name} remodel quote request"><input name="name" autocomplete="name" required /><input name="phone" type="tel" autocomplete="tel" required /><input name="city" value="${name}" /><textarea name="message" required></textarea><button type="submit">Request quote</button></form></section></main>`}
  return `<main data-jeriko-prerender="true"><section><p>Full-service bilingual remodeling company serving Oklahoma City and nearby areas.</p><h1>Brothers Remodeling OKC LLC</h1><p>Kitchen remodeling, bathroom remodeling, whole-home renovations, flooring, drywall, painting, exterior repairs, decks, fences, trim, doors, windows, garages, additions, and general repairs.</p><p>English and Spanish communication available for homeowners who want a clear remodeling path.</p><p><a href="/contact">Request a remodeling quote</a> or <a href="mailto:brothersremodelingokc@gmail.com" data-jeriko-track="email_click">email project photos</a>.</p><form action="/api/contact" method="post" data-jeriko-track="form_submit" aria-label="Remodel quote request"><input name="name" autocomplete="name" required /><input name="phone" type="tel" autocomplete="tel" required /><input name="email" type="email" autocomplete="email" /><textarea name="message" required></textarea><button type="submit">Request quote</button></form><h2>Services</h2><ul>${services.map(([slug,name])=>`<li><a href="/services/${slug}">${name}</a></li>`).join('')}</ul><h2>Service area</h2><ul>${cities.map(([slug,name])=>`<li><a href="/service-area/${slug}">${name} remodeling services</a></li>`).join('')}</ul></section></main>`;
}
function render(path, title, desc){let html=readFileSync(join(dist,'index.html'),'utf8');html=html.replace(/<title>.*?<\/title>/,`<title>${title}</title>`).replace(/<meta name="description" content="[^"]*"\s*\/>/,`<meta name="description" content="${esc(desc)}" />`).replace(/<div id="root"[^>]*>.*?<\/div>/s,`<div id="root" data-jeriko-prerender="true">${bodyFor(path)}</div>`);html=html.replace(/<link rel="canonical" href="[^"]*" \/>/g,'');html=html.replace('</head>',`<link rel="canonical" href="${siteUrl}${path==='/'?'':path}" /></head>`);const out=path==='/'?join(dist,'index.html'):join(dist,path,'index.html');mkdirSync(dirname(out),{recursive:true});writeFileSync(out,html);}
for (const r of routes) render(...r);
writeFileSync(join(dist,'robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${siteUrl}/sitemap.xml\n`);
writeFileSync(join(dist,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(([p])=>`<url><loc>${siteUrl}${p==='/'?'':p}</loc></url>`).join('')}</urlset>`);
writeFileSync(join(dist,'llms.txt'),`# Brothers Remodeling OKC LLC\n\nFull-service bilingual remodeling in Oklahoma City.\n\nSitemap: ${siteUrl}/sitemap.xml\n`);
for (const f of ['brothers-og.svg','brothers-hero.svg']) if (existsSync(`client/public/images/${f}`)) { mkdirSync(join(dist,'images'),{recursive:true}); copyFileSync(`client/public/images/${f}`, join(dist,'images',f)); }
console.log(`SEO prerendered ${routes.length} routes into ${dist}`);
